### ISSUE TITLE
Bug in Aztec C 3.4 preprocessor

### ISSUE THREAD

**Issue by johnsonjh** [tsupplis/cpm86-crossdev#8]
### The problem

The Aztec C 3.4 preprocessor has a bug which makes redefining a "reserved" keyword a fatal error.

This is **not** standard behavior (even for K&R).  At best it should be a warning and not a fatal error (in my opinion).

Aztec C 3.4's preprocessor makes this a true bug (and even worse) because it doesn't allow redefining some "keywords" it doesn't even support, like `const` and `void`, which prevents perfectly valid and idiomatic C code from compiling, for example, the following `test.c`:

```c
#include <stdio.h>
#ifndef __STDC__
# define const
# define void
#endif

int main(void) {
  const int x = 42;
  printf("%d\n");
  return 0;
}
```

This code is valid for any pre-ANSI compiler and also ANSI C (where `const` and `void` are supported keywords).

It fails to compile with Aztec C 3.4.

```
$ aztec34_cc test.c
Aztec C 8086 3.40a 7-3-86 (C) 1982,83,84,85 by Manx Software Systems, Inc.
# define const
              ^
test.c:4: ERROR 115: keyword redefined: const
# define void
             ^
test.c:5: ERROR 115: keyword redefined: void
2 errors
```

Historical Aztec C source code commonly uses a workaround (due to it being the documented workaround in the printed manual), as in this `test_aztec.c`:

```c
#include <stdio.h>
#ifdef __STDC__
# define CONST const
# define VOID void
#else
# define CONST
# define VOID
#endif

int main(VOID) {
  CONST int x = 42;
  printf("%d\n");
  return 0;
}
```

That works fine.  It's not idiomatic C but still common enough in old source code, but sort of gross and shouldn't be necessary.

The "protected" keywords that trigger the `ERROR 115` if you try to redefine them are `auto`, `break`, `case`, `char`, `const`, `continue`, `default`, `do`, `double`, `else`, `enum`, `extern`, `float`, `for`, `goto`, `if`, `int`, `long`, `register`, `return`, `short`, `signed`, `sizeof`, `static`, `struct`, `switch`, `typedef`, `union`, `unsigned`, `void`, `volatile`, and `while`.

Technically a pre-ANSI compiler, unlike an ANSI C compiler, can decide it's illegal to redefine reserved keywords, but not allowing you to redefine `const`, `volatile`, and `void` is a bug -- those are **not** even keywords recognized by Aztec C 3.4!

---

### Solution

Unless I totally missed it, I don't think we have the source code to the Aztec C 3.4 compiler.

The Aztec C 3.4 preprocessor is integrated into the compiler binaries (`cc.exe` and `ccb.exe`).

* It's trivial to patch `aztec34/bin/ccb.exe` and `aztec34/bin/cc.exe` to allow redefining `const`, `volatile`, and `void`:

   ```
   $ radiff2 ccb.exe.orig ccb.exe | column -t
   0x0000ab7f  636f6e7374        =>  0000000000        0x0000ab7f
   0x0000ac1c  766f6964          =>  00000000          0x0000ac1c
   0x0000ac21  766f6c6174696c65  =>  0000000000000000  0x0000ac21
   ```

   ```
   $ radiff2 cc.exe.orig cc.exe | column -t
   0x000150cf  636f6e7374        =>  0000000000        0x000150cf
   0x0001516c  766f6964          =>  00000000          0x0001516c
   0x00015171  766f6c6174696c65  =>  0000000000000000  0x00015171
   ```

If you wanted to, I could go further, disassemble the binaries, and patch them so redefining any of the actual reserved keywords gives a non-fatal warning instead of an error, but I think just fix described above is OK for Aztec 3.4.

None of this applies to Aztec 4.2 as it *does* allow you to redefine keywords (as ANSI C should).

**Comment by johnsonjh** [comment]
Here is a patcher I just tested, I can use to make a PR, if you want:

```sh
#!/bin/sh
# Copyright (c) 2026 Jeffrey H. Johnson <johnsonjh.dev@gmail.com>
# SPDX-License-Identifier: MIT-0
# Aztec C 3.4 preprocessor patch v0.3

set -eu

patch_file()
{
  file="${1}"
  offset="${2}"
  data="${3}"
  printf '%b' "${data}" \
    | dd of="${file}" bs=1 seek="${offset}" conv=notrunc 2> /dev/null
}

patch_one()
{
  infile="${1}"
  backup="${infile}.bak"
  base=${infile##*/}

  if [ ! -f "${infile}" ]; then
    printf '%s\n' "FATAL: '${infile}' not found" >&2
    exit 1
  fi

  if [ -e "${backup}" ]; then
    printf '%s\n' "FATAL: '${backup}' already exists, aborting!" >&2
    exit 1
  fi

  mv -f "${infile}" "${backup}"
  cp -f "${backup}" "${infile}"

  case ${base} in
  cc.exe)
    patch_file "${infile}" 86223 '\x00\x00\x00\x00\x00'
    patch_file "${infile}" 86380 '\x00\x00\x00\x00'
    patch_file "${infile}" 86385 '\x00\x00\x00\x00\x00\x00\x00\x00'
    ;;
  ccb.exe)
    patch_file "${infile}" 43903 '\x00\x00\x00\x00\x00'
    patch_file "${infile}" 44060 '\x00\x00\x00\x00'
    patch_file "${infile}" 44065 '\x00\x00\x00\x00\x00\x00\x00\x00'
    ;;
  *)
    printf '%s\n' "FATAL: unknown file '${infile}'" >&2
    exit 1
    ;;
  esac

  printf '%s\n' "Patched '${infile}'; original saved as '${backup}'"
}

patch_one "share/aztec34/bin/cc.exe"
patch_one "share/aztec34/bin/ccb.exe"
```

**Comment by tsupplis** [comment]
Super, yes please, if you can push a PR ...

**Comment by johnsonjh** [comment]
> Super, yes please, if you can push a PR ...

Will do.
